get:
  summary: GET quotas-settings (placeholder)
  description: GET quotas-settings (placeholder)
  responses:
    200:
      description: OK
      schema:
        $ref: ../../responses/FB1.8/quota-setting-get-response.yaml

  tags:
  - Quotas

patch:
  summary: PATCH quotas-settings (placeholder)
  description: PATCH quotas-settings (placeholder)
  parameters:
  - name: quota-setting
    in: body
    required: true
    schema:
      $ref: ../../models/FB1.8/quota-setting.yaml

  responses:
    200:
      description: OK
      schema:
        $ref: ../../responses/FB1.8/quota-setting-response.yaml

  tags:
  - Quotas
