description: Global settings for syslog servers.
properties:
  ca_certificate:
    description: The certificate of the certificate authority (CA) that signed the
      certificate(s) of the directory server, which is used to validate the authenticity
      of the configured servers.
    type: string
  tls_audit_enabled:
    description: Returns a value of `true` if messages that are necessary in order
      to audit TLS negotiations performed by the array are forwarded to the configured
      syslog servers.
    type: boolean
type: object
